# Generated by Django 3.2.8 on 2021-11-01 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Site', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_profit', models.IntegerField()),
                ('article_code', models.CharField(max_length=100)),
                ('division', models.IntegerField()),
                ('gestionnaire', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('planning', models.CharField(max_length=100)),
                ('commentaire', models.TextField(max_length=1000)),
                ('cycle_appro', models.IntegerField()),
                ('cycle_manuf', models.IntegerField()),
                ('cle_horizon', models.IntegerField()),
                ('delai_securite', models.IntegerField()),
                ('temps_reception', models.IntegerField()),
                ('cle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100)),
                ('date_dispo', models.DateField(auto_now=True)),
                ('element', models.CharField(max_length=100)),
                ('ordre', models.IntegerField()),
                ('message', models.IntegerField()),
                ('date_reordo', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherence.division')),
            ],
        ),
    ]
